//! Data output module for exporting results to CSV.
//!
//! Exports all analysis results in a format suitable for visualization
//! with gnuplot, including Jaccard curves, inversion radius estimates,
//! and regression forecasts.

use crate::inversion::{HistogramBin, InversionAnalysis};
use crate::regression::{ForecastPoint, IntervalRegression, JointCorridor};
use std::error::Error;
use std::fs::File;
use std::io::Write;

/// Exports all analysis results to CSV files for visualization.
pub fn export_results(
    analyses: &[InversionAnalysis],
    regression: Option<&IntervalRegression>,
    forecast: &[ForecastPoint],
    histogram_bins: &[HistogramBin],
    joint_corridor: Option<&JointCorridor>,
    output_dir: &str,
) -> Result<(), Box<dyn Error>> {
    std::fs::create_dir_all(format!("{}/report/traces", output_dir))?;

    export_main_data(analyses, regression, forecast, output_dir)?;
    export_jaccard_curves(analyses, output_dir)?;
    export_profiles(analyses, output_dir)?;
    export_regression_data(regression, forecast, output_dir)?;
    export_histogram_data(histogram_bins, output_dir)?;

    if let Some(corridor) = joint_corridor {
        export_joint_corridor(corridor, output_dir)?;
        export_informational_set(corridor, output_dir)?;
    }

    println!("\nExported results to:");
    println!(
        "  {}/report/traces/plot_data.csv - Main analysis data",
        output_dir
    );
    println!(
        "  {}/report/traces/jaccard_curves.csv - Jaccard index curves",
        output_dir
    );
    println!(
        "  {}/report/traces/profiles.csv - Temperature profiles",
        output_dir
    );
    println!(
        "  {}/report/traces/regression_data.csv - Regression and forecast data",
        output_dir
    );
    println!(
        "  {}/report/traces/histogram_data.csv - Binned histogram data",
        output_dir
    );
    println!(
        "  {}/report/traces/joint_corridor_forecast.csv - Joint corridor (Alg 3.7)",
        output_dir
    );

    Ok(())
}

/// Exports the main analysis data to plot_data.csv.
fn export_main_data(
    analyses: &[InversionAnalysis],
    regression: Option<&IntervalRegression>,
    forecast: &[ForecastPoint],
    output_dir: &str,
) -> Result<(), Box<dyn Error>> {
    let mut file = File::create(format!("{}/report/traces/plot_data.csv", output_dir))?;

    writeln!(
        file,
        "# Globus-M2 Tokamak Inversion Radius Analysis Results"
    )?;
    writeln!(file, "# Generated by interval-regression-tokamak")?;
    writeln!(file)?;

    // Section 1: Inversion radius estimates
    writeln!(file, "# Section 1: Inversion Radius Estimates")?;
    writeln!(file, "# shot_number,time_before,time_after,bt_ip_ratio,r_inv_point,r_inv_low,r_inv_high,r_inv_ext_low,r_inv_ext_high,max_jaccard_index,is_consistent,is_consistent_ext")?;

    for a in analyses {
        let max_ji = a
            .jaccard_curve
            .iter()
            .map(|(_, ji)| *ji)
            .fold(0.0_f64, f64::max);

        writeln!(
            file,
            "{},{:.2},{:.2},{:.6},{:.3},{:.3},{:.3},{:.3},{:.3},{:.6},{},{}",
            a.shot_number,
            a.time_before,
            a.time_after,
            a.bt_ip_ratio,
            a.r_inv_point,
            a.r_inv_low,
            a.r_inv_high,
            a.r_inv_ext_low,
            a.r_inv_ext_high,
            max_ji,
            if a.is_consistent { 1 } else { 0 },
            if a.is_consistent_ext { 1 } else { 0 }
        )?;
    }

    // Section 2: Regression results
    if let Some(reg) = regression {
        writeln!(file)?;
        writeln!(file, "# Section 2: Regression Results")?;
        writeln!(file, "# type,slope,intercept,slope_lower,slope_upper,intercept_lower,intercept_upper,r_squared")?;
        writeln!(
            file,
            "regression,{:.6},{:.3},{:.6},{:.6},{:.3},{:.3},{:.6}",
            reg.slope,
            reg.intercept,
            reg.slope_interval.lower,
            reg.slope_interval.upper,
            reg.intercept_interval.lower,
            reg.intercept_interval.upper,
            reg.r_squared
        )?;
    }

    // Section 3: Forecast data
    if !forecast.is_empty() {
        writeln!(file)?;
        writeln!(file, "# Section 3: Forecast Data")?;
        writeln!(file, "# bt_ip,r_inv_point,r_inv_lower,r_inv_upper")?;

        for fp in forecast {
            writeln!(
                file,
                "{:.6},{:.3},{:.3},{:.3}",
                fp.bt_ip, fp.r_inv_point, fp.r_inv_lower, fp.r_inv_upper
            )?;
        }
    }

    Ok(())
}

/// Exports histogram bin data to histogram_data.csv.
fn export_histogram_data(bins: &[HistogramBin], output_dir: &str) -> Result<(), Box<dyn Error>> {
    let mut file = File::create(format!("{}/report/traces/histogram_data.csv", output_dir))?;

    writeln!(file, "# Binned Inversion Radius Histogram Data")?;
    writeln!(
        file,
        "# bt_ip_center,r_inv_mean,r_inv_low,r_inv_high,r_inv_ext_low,r_inv_ext_high,count"
    )?;

    for bin in bins {
        writeln!(
            file,
            "{:.6},{:.3},{:.3},{:.3},{:.3},{:.3},{}",
            bin.bt_ip_center,
            bin.r_inv_mean,
            bin.r_inv_interval.lower,
            bin.r_inv_interval.upper,
            bin.r_inv_ext_interval.lower,
            bin.r_inv_ext_interval.upper,
            bin.count
        )?;
    }

    Ok(())
}

/// Exports the joint corridor forecast to joint_corridor_forecast.csv.
fn export_joint_corridor(corridor: &JointCorridor, output_dir: &str) -> Result<(), Box<dyn Error>> {
    let mut file = File::create(format!(
        "{}/report/traces/joint_corridor_forecast.csv",
        output_dir
    ))?;

    writeln!(file, "# Joint Corridor Forecast Data (Algorithm 3.7)")?;

    // Export special lines in header
    if let Some((slope, intercept)) = corridor.mass_center_line() {
        writeln!(
            file,
            "# Mass Center Line: slope={:.6}, intercept={:.3}",
            slope, intercept
        )?;
    }
    if let Some((slope, intercept)) = corridor.diagonal_center_line() {
        writeln!(
            file,
            "# Diagonal Center Line: slope={:.6}, intercept={:.3}",
            slope, intercept
        )?;
    }

    writeln!(file, "# bt_ip,r_inv_center,r_inv_lower,r_inv_upper")?;

    // Extend range to 0.010 to match Figure 3.9
    let x_min = 0.0016;
    let x_max = 0.0100;
    let forecast = corridor.forecast(x_min, x_max, 200);

    for fp in forecast {
        writeln!(
            file,
            "{:.6},{:.3},{:.3},{:.3}",
            fp.bt_ip, fp.r_inv_point, fp.r_inv_lower, fp.r_inv_upper
        )?;
    }

    Ok(())
}

/// Exports the set of admissible parameters (informational set) to informational_set.csv.
fn export_informational_set(
    corridor: &JointCorridor,
    output_dir: &str,
) -> Result<(), Box<dyn Error>> {
    let mut file = File::create(format!(
        "{}/report/traces/informational_set.csv",
        output_dir
    ))?;

    writeln!(file, "# Informational Set of Admissible Parameters (a, b)")?;
    writeln!(file, "# slope,intercept")?;

    for (a, b) in &corridor.lines {
        writeln!(file, "{:.10},{:.10}", a, b)?;
    }

    Ok(())
}

/// Exports Jaccard curves for each analysis.
fn export_jaccard_curves(
    analyses: &[InversionAnalysis],
    output_dir: &str,
) -> Result<(), Box<dyn Error>> {
    let mut file = File::create(format!("{}/report/traces/jaccard_curves.csv", output_dir))?;

    writeln!(file, "# Jaccard Index Curves for Each Sawtooth Event")?;
    writeln!(file, "# shot_number,time_before,radius,jaccard_index")?;

    for a in analyses {
        for (r, ji) in &a.jaccard_curve {
            writeln!(
                file,
                "{},{:.2},{:.3},{:.6}",
                a.shot_number, a.time_before, r, ji
            )?;
        }
    }

    Ok(())
}

/// Exports temperature profiles.
fn export_profiles(analyses: &[InversionAnalysis], output_dir: &str) -> Result<(), Box<dyn Error>> {
    let mut file = File::create(format!("{}/report/traces/profiles.csv", output_dir))?;

    writeln!(file, "# Temperature Profiles and Compatibility Corridors")?;
    writeln!(
        file,
        "# profile_type,shot_number,time,radius,temperature,temp_lower,temp_upper"
    )?;

    for a in analyses {
        for (r, t) in &a.profile_before {
            writeln!(
                file,
                "before,{},{:.2},{:.3},{:.6},,",
                a.shot_number, a.time_before, r, t
            )?;
        }
        for (r, t) in &a.profile_after {
            writeln!(
                file,
                "after,{},{:.2},{:.3},{:.6},,",
                a.shot_number, a.time_after, r, t
            )?;
        }
        for (r, lower, upper) in &a.corridor_before {
            writeln!(
                file,
                "corridor_before,{},{:.2},{:.3},,{:.6},{:.6}",
                a.shot_number, a.time_before, r, lower, upper
            )?;
        }
        for (r, lower, upper) in &a.corridor_after {
            writeln!(
                file,
                "corridor_after,{},{:.2},{:.3},,{:.6},{:.6}",
                a.shot_number, a.time_after, r, lower, upper
            )?;
        }
    }

    Ok(())
}

/// Exports regression and forecast data.
fn export_regression_data(
    regression: Option<&IntervalRegression>,
    forecast: &[ForecastPoint],
    output_dir: &str,
) -> Result<(), Box<dyn Error>> {
    let mut file = File::create(format!("{}/report/traces/regression_data.csv", output_dir))?;

    writeln!(file, "# Regression and Forecast Data for R_inv vs B_T/I_P")?;

    if let Some(reg) = regression {
        writeln!(
            file,
            "# Regression: R_inv = {:.4} * (B_T/I_P) + {:.2}",
            reg.slope, reg.intercept
        )?;
        writeln!(file, "# R-squared: {:.4}", reg.r_squared)?;
        writeln!(file)?;

        writeln!(file, "# Data points used in regression")?;
        writeln!(file, "# bt_ip,r_inv")?;
        for (x, y) in &reg.data_points {
            writeln!(file, "{:.6},{:.3}", x, y)?;
        }
    }

    if !forecast.is_empty() {
        writeln!(file)?;
        writeln!(file, "# Forecast line with uncertainty bands")?;
        writeln!(file, "# bt_ip,r_inv_center,r_inv_lower,r_inv_upper")?;

        for fp in forecast {
            writeln!(
                file,
                "{:.6},{:.3},{:.3},{:.3}",
                fp.bt_ip, fp.r_inv_point, fp.r_inv_lower, fp.r_inv_upper
            )?;
        }
    }

    Ok(())
}
